### PR TITLE
MIST-399 Copy agent.json into place when installing mistify-agent

### PR DESCRIPTION
**Pull request by TauZero**
Related to https://github.com/mistifyio/lochness-ansible/pull/30

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent/39)

### CODE REVIEW

**Comment by mmlb** [comment]
<sup>**[Makefile, line 15 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39#-JmoBpckSBwsWQ1K_5Kl)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/7de937284dd7b324d3bd2fed6a88944a949844f8/Makefile#L15)):</sup>
You want to prefix `$(CONF_DIR)` with `$(DESTDIR)` like below.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39)

**Comment by StevenIsaacs** [comment]
<sup>**[Makefile, line 15 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39#-JmoBqKWxIXCo74SH2aK)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/7de937284dd7b324d3bd2fed6a88944a949844f8/Makefile#L15)):</sup>
I believe the $(CONF_DIR) needs to be prefixed with $(DESTDIR).

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39)

**Comment by TauZero** [comment]
<sup>**[Makefile, line 15 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39#-JmoBpckSBwsWQ1K_5Kl)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/7de937284dd7b324d3bd2fed6a88944a949844f8/Makefile#L15)):</sup>
Hmm. The lochness-ansible role for mistify-agent is looking directly at `/opt/mistify/sbin/mistify-agent` (which would be `$(SBIN_DIR)/mistify-agent`) and `/etc/mistify/agent.json` (which would be `$(CONF_DIR)/agent.json`) for the config. It doesn't seem that any of the ansible roles take into consideration a `DESTDIR`.

---

<sup>**[Makefile, line 15 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39#-JmoBqKWxIXCo74SH2aK)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/7de937284dd7b324d3bd2fed6a88944a949844f8/Makefile#L15)):</sup>
See reply to mm above.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39)

**Comment by mmlb** [comment]
<sup>**[Makefile, line 15 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39#-JmoBpckSBwsWQ1K_5Kl)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/7de937284dd7b324d3bd2fed6a88944a949844f8/Makefile#L15)):</sup>
DESTDIR is for when being built by buildroot. buildroot will call `make install DESTDIR=$someplace`, which it then packs up $someplace as the *package*. Otherwise you would be installing into your machine's `/etc/mistify` directory and buildroot would have no idea to go there.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39)

**Comment by TauZero** [comment]
<sup>**[Makefile, line 15 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39#-JmoBpckSBwsWQ1K_5Kl)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/7de937284dd7b324d3bd2fed6a88944a949844f8/Makefile#L15)):</sup>
Ah, I see. `DESTDIR` is just for the build process and nothing needs to know about it afterward. Fixed

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39)

**Comment by mmlb** [comment]
Reviewed files:
- Makefile @ r2

---

<sup>**[Makefile, line 15 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39#-JmoBpckSBwsWQ1K_5Kl)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/7de937284dd7b324d3bd2fed6a88944a949844f8/Makefile#L15)):</sup>
Youngins and the blissful ignorance of the wonders that is Makefiles... :)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/39)

**Pull request merged**
