### PR TITLE
MIST-420 Agent-level job logging

### PR DESCRIPTION
**Pull request by TauZero**
Instead of keeping a job log per-guest, which doesn't exist for pre-create actions like image fetching or post-deleting, maintain a job log at the agent level. Each guest still has their own job runner, and the agent now has one as well.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent/43)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed files:
- cmd/mistify-agent/main.go @ r1
- context.go @ r1
- guest.go @ r1
- guestJobLog.go @ r1
- http.go @ r1

---

<sup>**[guestRunner.go, line 95 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUjt4Tq2fa76jeECTO)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/guestRunner.go#L95)):</sup>
just do `return context.GetGuestRunner("agent")`

---

<sup>**[image.go, line 21 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUkLRM7TG7zg-Ypg2-)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/image.go#L21)):</sup>
We should probably go by and change these codes to `http.Status*` codes later on.

---

<sup>**[jobLog.go, line 35 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUrnn6tkdiCu69EvL5)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L35)):</sup>
Apparently its a go idiom to put the mutex above the fields it protects, can you do that.

---

<sup>**[jobLog.go, line 35 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUsBzeFqoa6eK5HwtJ)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L35)):</sup>
ModifyMutext needs to be grabbed for all uses of data it protects so you are currently racing in places where its missing. Maybe change it to a RWMutex?

---

<sup>**[jobLog.go, line 78 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUqlEMzG8IAUdGyOUL)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L78)):</sup>
Why not extract this into a helper func that takes in the `JobLog` and limit and does the limiting, and reversing in there? Right now this and `GetLatestGuestJobs` have slightly different variable names and reversal method for effectively the same func.

---

<sup>**[jobLog.go, line 80 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUnFoVh5GKIKxLo4ND)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L80)):</sup>
I presume that this is so the http api returns an empty struct vs nil...?

---

<sup>**[jobLog.go, line 86 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUr8PncOYypYYSsYe0)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L86)):</sup>
If we had a jobsSort type == `[]*Job` and make it satisfy `sort.Interface` we could just call `sort.Reverse` with that.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43)

**Comment by TauZero** [comment]
<sup>**[guestRunner.go, line 95 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUjt4Tq2fa76jeECTO)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/guestRunner.go#L95)):</sup>
I've definitely had it complain about returning multiple returns in one shot before, but it compiled this time. Fixed.

---

<sup>**[image.go, line 21 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUkLRM7TG7zg-Ypg2-)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/image.go#L21)):</sup>
Agreed.

---

<sup>**[jobLog.go, line 35 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUrnn6tkdiCu69EvL5)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L35)):</sup>
Done

---

<sup>**[jobLog.go, line 35 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUsBzeFqoa6eK5HwtJ)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L35)):</sup>
Changed to RWMutex, pulled some functionality out into private methods without locks to be used within public methods that do lock, added appropriate locking to public methods.

---

<sup>**[jobLog.go, line 78 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUqlEMzG8IAUdGyOUL)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L78)):</sup>
`GetLatestJobs` can use `jobs` array directly while `GetLatestGuestJobs` has to use at the guest's index and then look up the actual jobs.

---

<sup>**[jobLog.go, line 80 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUnFoVh5GKIKxLo4ND)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L80)):</sup>
Yep

---

<sup>**[jobLog.go, line 86 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUr8PncOYypYYSsYe0)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L86)):</sup>
We're not reverse sorting, just reversing the existing order. Seems less efficient to do it with `sort.Reverse`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43)

**Comment by mmlb** [comment]
Reviewed files:
- image.go @ r1

---

<sup>**[jobLog.go, line 52 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoZrqbw1GJB0Z8xYIHe)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/369d32bbc96eff15b82f4047e517fc63f4082e2e/jobLog.go#L52)):</sup>
Change this to something like "Must be called with ModifyMutex held", so we know *why* it should not be called directly.

---

<sup>**[jobLog.go, line 86 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUr8PncOYypYYSsYe0)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L86)):</sup>
Hmm wtf, that vacation messed with my code comprehension skills. 

---

<sup>**[jobLog.go, line 88 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUqlEMzG8IAUdGyOUL)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L88)):</sup>
Ah yes, I  see. Hmm, I stared at this code for a while trying to figure out if it was in fact doing the same thing (as I thought it was). I thought positions was a terrible name for the joblog :/.

---

<sup>**[jobLog.go, line 212 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoZylPacaiXlKjg_jUG)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/369d32bbc96eff15b82f4047e517fc63f4082e2e/jobLog.go#L212)):</sup>
IMO these Context methods should not be here. Its confusing that I have to keep two different contexts (ha, not intended) in mind when reading the `jobLog` file, Create/GetJobLog really only ever deal with Context members except where it can call a hypothetical `joblog.New()`. This kind of stems from aversion to sub-packages, but I think we should fix this.

---

<sup>**[jobLog.go, line 293 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoZsuNgjAKAxAGeOh3Z)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/369d32bbc96eff15b82f4047e517fc63f4082e2e/jobLog.go#L293)):</sup>
\n

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43)

**Comment by mmlb** [comment]
Reviewed files:
- guestRunner.go @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43)

**Comment by mmlb** [comment]
<sup>**[README.md, line 485 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-Jo_0fiHFVOgBx8rybl0)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/369d32bbc96eff15b82f4047e517fc63f4082e2e/README.md#L485)):</sup>
need to regen?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43)

**Comment by TauZero** [comment]
<sup>**[jobLog.go, line 52 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoZrqbw1GJB0Z8xYIHe)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/369d32bbc96eff15b82f4047e517fc63f4082e2e/jobLog.go#L52)):</sup>
Done.

---

<sup>**[jobLog.go, line 88 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUqlEMzG8IAUdGyOUL)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L88)):</sup>
Done.

---

<sup>**[jobLog.go, line 99 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoUr8PncOYypYYSsYe0)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f8cc670d5577d886de589dbcaed5cd934404fbca/jobLog.go#L99)):</sup>
Done.

---

<sup>**[jobLog.go, line 212 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoZylPacaiXlKjg_jUG)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/369d32bbc96eff15b82f4047e517fc63f4082e2e/jobLog.go#L212)):</sup>
(after Slack discussion) moved to `context.go`

---

<sup>**[jobLog.go, line 293 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-JoZsuNgjAKAxAGeOh3Z)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/369d32bbc96eff15b82f4047e517fc63f4082e2e/jobLog.go#L293)):</sup>
Done.

---

<sup>**[README.md, line 485 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43#-Jo_0fiHFVOgBx8rybl0)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/369d32bbc96eff15b82f4047e517fc63f4082e2e/README.md#L485)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43)

**Comment by mmlb** [comment]
Reviewed files:
- context.go @ r3
- jobLog.go @ r3
- README.md @ r3

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/43)

**Pull request merged**
