### PR TITLE
[MIST-372] Use the default setup for logrus

### PR DESCRIPTION
**Pull request by rsterbin**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent/31)

### CODE REVIEW

**Comment by TauZero** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31)







---

<sup>**[cmd/mistify-agent/main.go, line 20 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31#-JkZSY53ukWVjHyPhD58)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/7b5b9e5d8ef8eeb853a4ca024b6b272484c48706/cmd/mistify-agent/main.go#L20)):</sup>
`if err := logx.DefaultSetup(logLevel); err != nil {`

---

**Comment by rsterbin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31)







---

<sup>**[cmd/mistify-agent/main.go, line 20 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31#-JkZSY53ukWVjHyPhD58)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/7b5b9e5d8ef8eeb853a4ca024b6b272484c48706/cmd/mistify-agent/main.go#L20)):</sup>
Done.

---

**Comment by TauZero** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31)

Reviewed files:
- cmd/mistify-agent/main.go @ r2





---

<sup>**[examples/simple-subagent/main.go, line 48 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31#-JkZZG78OPJVFzFurCa7)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f5d3d720d3988fe29be1c3b37e5cb5f228120181/examples/simple-subagent/main.go#L48)):</sup>
`if err := logx.DefaultSetup("info"); err != nil`

---

<sup>**[examples/test-rpc-service/main.go, line 265 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31#-JkZZLnZWHVWJXH3i15z)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f5d3d720d3988fe29be1c3b37e5cb5f228120181/examples/test-rpc-service/main.go#L265)):</sup>
`if err := logx.DefaultSetup("info"); err != nil`

---

<sup>**[examples/webhook-post/main.go, line 101 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31#-JkZZNfweuKMmKJwdjb5)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f5d3d720d3988fe29be1c3b37e5cb5f228120181/examples/webhook-post/main.go#L101)):</sup>
`if err := logx.DefaultSetup("info"); err != nil`

---

**Comment by rsterbin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31)







---

<sup>**[examples/simple-subagent/main.go, line 48 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31#-JkZZG78OPJVFzFurCa7)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f5d3d720d3988fe29be1c3b37e5cb5f228120181/examples/simple-subagent/main.go#L48)):</sup>
Done.

---

<sup>**[examples/webhook-post/main.go, line 101 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31#-JkZZNfweuKMmKJwdjb5)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f5d3d720d3988fe29be1c3b37e5cb5f228120181/examples/webhook-post/main.go#L101)):</sup>
Done.

---

**Comment by TauZero** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31)

Reviewed files:
- examples/simple-subagent/main.go @ r3
- examples/test-rpc-service/main.go @ r3
- examples/webhook-post/main.go @ r3





---

**Comment by mmlb** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31)

Reviewed files:
- cmd/mistify-agent/main.go @ r2
- examples/simple-subagent/main.go @ r3
- examples/test-rpc-service/main.go @ r3
- examples/webhook-post/main.go @ r3





---

**Comment by mmlb** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31)







---

<sup>**[examples/test-rpc-service/main.go, line 265 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31#-JkZZLnZWHVWJXH3i15z)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f5d3d720d3988fe29be1c3b37e5cb5f228120181/examples/test-rpc-service/main.go#L265)):</sup>
Looks done to me

---

**Comment by rsterbin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31)







---

<sup>**[examples/test-rpc-service/main.go, line 265 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/31#-JkZZLnZWHVWJXH3i15z)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/f5d3d720d3988fe29be1c3b37e5cb5f228120181/examples/test-rpc-service/main.go#L265)):</sup>
Done.

---

**Pull request merged**
