### PR TITLE
MIST-421 Combine zfs and container image handling

### PR DESCRIPTION
**Pull request by TauZero**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent/44)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed files:
- containerImage.go @ r1
- examples/test-rpc-service/main.go @ r1
- http.go @ r1
- rpc/containerImage.go @ r1
- rpc/image.go @ r1

---

<sup>**[image.go, line 14 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JoixTs6s3ispXlF1BHh)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L14)):</sup>
should we add a type for `kvm`, what if we only want to see those?

---

<sup>**[image.go, line 44 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-Joiy-bbym10y6SIdT-w)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L44)):</sup>
did you mean to continue? If not won't the error message printed later be basically useless?

---

<sup>**[image.go, line 97 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojLw79VH7zq9mBXvm3)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L97)):</sup>
should we print some sort of error if `len(images) > 1` or `len(images) != 1`?

---

<sup>**[image.go, line 118 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojMJtUXed2QJnT71tF)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L118)):</sup>
err2? This does not seem necessary.

---

<sup>**[image.go, line 126 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojMTvHAVmd8P1ClAtr)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L126)):</sup>
ditto.

---

<sup>**[image.go, line 146 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojMZXLXAawj2IpPLBM)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L146)):</sup>
Can I get an empty line here?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44)

**Comment by TauZero** [comment]
<sup>**[image.go, line 44 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-Joiy-bbym10y6SIdT-w)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L44)):</sup>
Good catch. Fixed

---

<sup>**[image.go, line 97 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojLw79VH7zq9mBXvm3)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L97)):</sup>
Yeah. Added.

---

<sup>**[image.go, line 118 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojMJtUXed2QJnT71tF)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L118)):</sup>
`err` from `imageMultiQuery` is an `HTTPErrorMessage` while these others are regular `error`. I've updated the former to be `mqErr` and these two to just `err`.

---

<sup>**[image.go, line 126 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojMTvHAVmd8P1ClAtr)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L126)):</sup>
See err2 comment

---

<sup>**[image.go, line 146 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojMZXLXAawj2IpPLBM)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L146)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44)

**Comment by TauZero** [comment]
<sup>**[image.go, line 14 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JoixTs6s3ispXlF1BHh)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L14)):</sup>
The way the backends are right now, it's essentially contaner->agent-docker and [everything else]->agent-image. If we want to require image types and lock them down to a set of `{"kvm","container"}` we can tighten things up. I'd want to do that in a separate card/PR so any handling refactors can be done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44)

**Comment by trisk** [comment]
<sup>**[http.go, line 89 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojhZVxwvdB0OkLod_K)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/http.go#L89)):</sup>
Is there some way to actually enforce the type list instead of using validation filters? Or a more declarative interface than http.HandleFunc?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44)

**Comment by trisk** [comment]
Reviewed files:
- containerImage.go @ r1
- examples/test-rpc-service/main.go @ r1
- rpc/containerImage.go @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44)

**Comment by mmlb** [comment]
<sup>**[image.go, line 14 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JoixTs6s3ispXlF1BHh)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L14)):</sup>
I thought this would be a good place to start that off. This front-end is really doing `container -> agent-docker`, `[everything else] -> (agent-docker, agent-image)` no? There is no *only* `agent-image` get/list.

---

<sup>**[image.go, line 101 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojgvyCwxFoYzwx6xIj)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/8bb85426953a17a43eb3a46976bfb81fc792d570/image.go#L101)):</sup>
Maybe stronger wording or a comment? This should be a total WTF right?

---

<sup>**[image.go, line 132 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojMJtUXed2QJnT71tF)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L132)):</sup>
Ahh I see.

---

<sup>**[image.go, line 160 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojMZXLXAawj2IpPLBM)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L160)):</sup>
Awwww yeah

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44)

**Comment by TauZero** [comment]
<sup>**[image.go, line 101 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojgvyCwxFoYzwx6xIj)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/8bb85426953a17a43eb3a46976bfb81fc792d570/image.go#L101)):</sup>
It would happen if both the `agent-image` and `agent-docker` managed to store an image under the same id. Once we move to our own image server, which will assign ids, it should become very unlikely.  Added a comment since all errors should be getting investigated already.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44)

**Comment by TauZero** [comment]
<sup>**[http.go, line 89 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojhZVxwvdB0OkLod_K)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/http.go#L89)):</sup>
If we don't want to do it in the handlers, it's possible we can make a middleware to do it (which is annoying in `mistify-agent` in particular). For now, I think doing it in the handlers is cleanest.

---

<sup>**[image.go, line 14 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JoixTs6s3ispXlF1BHh)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L14)):</sup>
You can pass in whatever value you want for `type` and as long as it's not "container", it'll limit `imageTypes` to effectively "not-container" (and as of now, that means kvm from `agent-image`). 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44)

**Comment by mmlb** [comment]
Reviewed files:
- image.go @ r3

---

<sup>**[image.go, line 14 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JoixTs6s3ispXlF1BHh)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/cd21b246a8c6c3404d149acf46d18945280487d0/image.go#L14)):</sup>
ahhh, ok.

---

<sup>**[image.go, line 105 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44#-JojgvyCwxFoYzwx6xIj)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/8bb85426953a17a43eb3a46976bfb81fc792d570/image.go#L105)):</sup>
Got it.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44)

**Comment by trisk** [comment]
Reviewed files:
- http.go @ r1
- image.go @ r3
- rpc/image.go @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/44)

**Pull request merged**
