### PR TITLE
MIST-376 docker subagent integration

### PR DESCRIPTION
**Pull request by TauZero**
Treat containers as much like guests as possible.
Related:
https://github.com/mistifyio/lochness/pull/85
https://github.com/mistifyio/mistify-agent-docker/pull/1

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent/37)

### CODE REVIEW

**Comment by trisk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37)







---

<sup>**[cmd/mistify-agent/agent.json, line 174 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlRTGIhjuSlEP1Dekfu)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/5317a6591a8a125e61fa3474d473a02c212858a6/cmd/mistify-agent/agent.json#L174)):</sup>
Should be GetImage here

---

**Comment by TauZero** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37)







---

<sup>**[cmd/mistify-agent/agent.json, line 174 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlRTGIhjuSlEP1Dekfu)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/5317a6591a8a125e61fa3474d473a02c212858a6/cmd/mistify-agent/agent.json#L174)):</sup>
Done.

---

**Comment by trisk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37)

Reviewed files:
- .gitignore @ r1
- client/guest.go @ r1
- cmd/mistify-agent/agent.json @ r2
- config/config.go @ r1
- container.go @ r1
- containerImage.go @ r1
- examples/test-rpc-service/agent.json @ r1
- examples/test-rpc-service/main.go @ r1
- guest.go @ r1
- http.go @ r1
- rpc/container.go @ r1
- rpc/containerImage.go @ r1
- test.sh @ r1





---

<sup>**[cmd/mistify-agent/agent.json, line 262 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlRMYDEIEhEVixDMs4v)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/5317a6591a8a125e61fa3474d473a02c212858a6/cmd/mistify-agent/agent.json#L262)):</sup>
typo :)

---

**Comment by TauZero** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37)







---

<sup>**[cmd/mistify-agent/agent.json, line 262 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlRMYDEIEhEVixDMs4v)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/5317a6591a8a125e61fa3474d473a02c212858a6/cmd/mistify-agent/agent.json#L262)):</sup>
Fixed.

---

**Comment by trisk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37)

Reviewed files:
- cmd/mistify-agent/agent.json @ r3





---

**Comment by mmlb** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37)

Reviewed files:
- .gitignore @ r1
- client/guest.go @ r1
- cmd/mistify-agent/agent.json @ r3
- containerImage.go @ r1
- examples/test-rpc-service/agent.json @ r1
- examples/test-rpc-service/main.go @ r1
- rpc/container.go @ r1
- rpc/containerImage.go @ r1
- test.sh @ r1





---

<sup>**[config/config.go, line 52 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqAIj-9G8wi4QMVvOI)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/config/config.go#L52)):</sup>
Won't this list inhibit 3rd parties from plugging in their own plugins?

---

<sup>**[container.go, line 83 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqBWzOurR2kgCk4GUZ)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/container.go#L83)):</sup>
\n

---

<sup>**[container.go, line 100 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqBY67avVWqZaqOv8k)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/container.go#L100)):</sup>
\n

---

<sup>**[examples/test-rpc-service/main.go, line 303 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqCIIWJDPr2MBCk8Ul)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/examples/test-rpc-service/main.go#L303)):</sup>
poih? why isn't your right hand on the home row? :D

---

<sup>**[guest.go, line 288 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqCkdOsgUxPJXjJDkS)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/guest.go#L288)):</sup>
debugging or should this really be log?

---

<sup>**[http.go, line 124 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqD9RaB0k5TDvvfIfv)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/http.go#L124)):</sup>
Feels wrong. Can `/images/{id}/` handler lookup `id` flavor/type and then call the correct func?

---

<sup>**[test.sh, line 1 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqDqwTvE0k_imiVJLS)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/test.sh#L1)):</sup>
Definite candidate for robot

---

**Comment by TauZero** [comment]
---

<sup>**[config/config.go, line 52 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqAIj-9G8wi4QMVvOI)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/config/config.go#L52)):</sup>
They add their own plugins to the stages for these actions in `agent.json`. Bakins and I had a long discussion about subagents autoregistering actions and routes and whatnot early and decided against it for now.

---

<sup>**[container.go, line 83 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqBWzOurR2kgCk4GUZ)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/container.go#L83)):</sup>
Done

---

<sup>**[container.go, line 100 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqBY67avVWqZaqOv8k)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/container.go#L100)):</sup>
Done

---

<sup>**[examples/test-rpc-service/main.go, line 303 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqCIIWJDPr2MBCk8Ul)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/examples/test-rpc-service/main.go#L303)):</sup>
That would be too easy

---

<sup>**[guest.go, line 288 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqCkdOsgUxPJXjJDkS)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/guest.go#L288)):</sup>
Accidentally committed debug line. Removed.

---

<sup>**[http.go, line 124 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqD9RaB0k5TDvvfIfv)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/http.go#L124)):</sup>
The response structs looked different enough that I couldn't nicely unify them for normal and docker images and didn't want the `/images/*` endpoints to have unpredictable output. Also would be a pain, without a unified response image struct, to do the list with plain `/images`

---

<sup>**[test.sh, line 1 \[r3\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37#-JlqDqwTvE0k_imiVJLS)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/34b3a96d911f138f59be87ef4052badc82454ac5/test.sh#L1)):</sup>
Yup

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37)

**Comment by mmlb** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/37)

Reviewed files:
- config/config.go @ r1
- container.go @ r4
- guest.go @ r4
- http.go @ r1





---

**Pull request merged**
