### PR TITLE
MIST-557 Cleanup for golint, go vet, errcheck

### PR DESCRIPTION
**Pull request by TauZero**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent/50)

### CODE REVIEW

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by mmlb** [comment]
Ok to test

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/50)

**Comment by rizvfe00** [comment]
Ok to test

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 4 of 4 files at r3, 6 of 6 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, 10 of 10 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/50)

**Comment by TauZero** [comment]
The failing test is due to jenkins tests being moved around. The two passing tests (`mistify-agent-UnitTests` and `mistify-agent/mistify-agent-CodeAnalytics`) are the real ones.

**Pull request merged**
