### PR TITLE
[MIST-360] Moved agent and example subagents to pflag

### PR DESCRIPTION
**Pull request by rsterbin**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent/26)

### CODE REVIEW

**Comment by TauZero** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/26)

Reviewed files:
- cmd/mistify-agent/main.go @ r1
- examples/simple-subagent/main.go @ r1
- examples/test-rpc-service/main.go @ r1
- examples/webhook-post/main.go @ r1

---

You can remove the explicit help flags and handling thereof across the board; pflag adds the help flag and usage display automatically.

---

**Comment by rsterbin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/26)



---

Done.

---

**Comment by TauZero** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/26)

Reviewed files:
- cmd/mistify-agent/main.go @ r3
- examples/simple-subagent/main.go @ r3
- examples/test-rpc-service/main.go @ r3
- examples/webhook-post/main.go @ r3





---

**Comment by bakins** [comment]
LGTM

**Pull request merged**
