### PR TITLE
[MIST-359] Use logrus for logging

### PR DESCRIPTION
**Pull request by rsterbin**
Did not remove the internal log package -- thoughts?

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent/27)

### CODE REVIEW

**Comment by bakins** [comment]
We should probably remove the internal log package.

**Comment by rsterbin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/27)



---

Done.

---

**Comment by TauZero** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/27)

Reviewed files:
- cmd/mistify-agent/main.go @ r1
- context.go @ r1
- examples/simple-subagent/main.go @ r1
- examples/test-rpc-service/main.go @ r1
- examples/webhook-post/main.go @ r1
- guest.go @ r1
- guestRunner.go @ r1
- http.go @ r1
- log/log.go @ r2





---

**Comment by bakins** [comment]
LGTM

**Pull request merged**
