### PR TITLE
MIST-455 Fix middleware setup

### PR DESCRIPTION
**Pull request by TauZero**
Replace all of the non-standard signature wrappers and middleware with standard middleware functions. In doing so, use the gorilla/context instead of wrapping the request for keeping track extra of request data. Where it made sense, apply middleware to routers/subrouters instead of individual handlers.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-agent/48)

### CODE REVIEW

**Comment by bakins** [comment]
You can actually pass methods as handlers, i.e.:

```go
func (ctx *Context)GetTheThings(w ResponseWriter, r*Request) {
...
}

func main() {
    ctx := NewContext(....)
    r := mux.NewRouter()
    r.HandleFunc("/things", ctx.GetTheThings)
}
```

Didn't know this many months ago. This may help with a lot of the duplicate code.

**Comment by mmlb** [comment]
Review status: all files reviewed, 14 unresolved discussions, all commit checks successful.
Reviewed files:
- container.go @ r12
- guest.go @ r8, r10, r11, r13, r16
- guestRunner.go @ r8, r16
- http.go @ r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r13, r14, r15
- image.go @ r6, r14
- jobLog.go @ r7
- metrics.go @ r8
- README.md @ r16
- snapshot.go @ r9

---

<sup>**[guest.go, line 114 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYqoA1itnL-nVcV2Mo)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L114)):</sup>
hmmm, why wasn't this treated as an error? I dont see this as being valid, especially since we dont yet have logic to make sure it's unique/not already created.

---

<sup>**[guest.go, line 201 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYrsXGNUCqnRail0Rg)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L201)):</sup>
should not be exported...?

---

<sup>**[guest.go, line 309 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYs1nnVs2jhYxy9hTw)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L309)):</sup>
unexport?

---

<sup>**[guest.go, line 311 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYtouOnRlL_48timt3)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L311)):</sup>
hr is only being used in the error case, should it be moved into there?

---

<sup>**[guest.go, line 381 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYty2mWdIcn7zDC6Q9)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L381)):</sup>
unexport?

---

<sup>**[guest.go, line 423 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYumKBaIa6cwxS9R7H)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L423)):</sup>
err is not being used/logged here, so can just do `if <-doneChan != nil {`

---

<sup>**[guest.go, line 434 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYvS43TYbcNi2RTtoX)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L434)):</sup>
this return is unnecessary right?

---

<sup>**[guest.go, line 441 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYvjgzigfyr3dd_K-h)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L441)):</sup>
unexport?

---

<sup>**[guestRunner.go, line 232 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYvuTjlspvexC5od3j)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guestRunner.go#L232)):</sup>
unexport?

---

<sup>**[metrics.go, line 52 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYpfNPoqHe2FjYF43I)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/metrics.go#L52)):</sup>
If you move this into a `default:` case you can get rid of all returns

---

<sup>**[README.md, line 272 \[r16\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrZ1dYB2YHHplKM_8ua)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/fd02be42d22568a3db9b8e96a30337644a8ee232/README.md#L272)):</sup>
unexport?

---

<sup>**[snapshot.go, line 62 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYwiEUrtlW69ghULIo)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/06dbc058e567c83cd5799a39c355d79391d0a1d3/snapshot.go#L62)):</sup>
snuck in?

---

<sup>**[snapshot.go, line 94 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYx69nT6uvHTTd4FcY)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/06dbc058e567c83cd5799a39c355d79391d0a1d3/snapshot.go#L94)):</sup>
Can you add a comment here, not sure why its true when disk is empty

---

<sup>**[snapshot.go, line 122 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYxh2V-lfNWBpkWMhH)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/06dbc058e567c83cd5799a39c355d79391d0a1d3/snapshot.go#L122)):</sup>
hmm not sure if that previous comment should be included here also, but I think it is

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48)

**Comment by TauZero** [comment]
Review status: all files reviewed, 14 unresolved discussions, all commit checks successful.

---

<sup>**[guest.go, line 114 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYqoA1itnL-nVcV2Mo)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L114)):</sup>
Originally IDs were assigned by the `mistify-agent`. When we started doing stuff with `lochness` and `cguestd`, IDs were being assigned up at that level, so this was added to prevent `mistify-agent` from blowing away the existing id. Deciding/changing this behavior seems outside the scope of this task/PR. (this line wasn't actually changed)

---

<sup>**[guest.go, line 261 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYtouOnRlL_48timt3)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L261)):</sup>
True. Moved.

---

<sup>**[guest.go, line 317 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYumKBaIa6cwxS9R7H)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L317)):</sup>
Wasn't part of the PR, but an easy quick fix.

---

<sup>**[guest.go, line 328 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYvS43TYbcNi2RTtoX)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L328)):</sup>
Unnecessary currently. Not a terrible idea when there's a chance more could be added after this if condition. (also, line not changed in PR)

---

<sup>**[metrics.go, line 52 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYpfNPoqHe2FjYF43I)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/metrics.go#L52)):</sup>
Done.

---

<sup>**[snapshot.go, line 62 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYwiEUrtlW69ghULIo)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/06dbc058e567c83cd5799a39c355d79391d0a1d3/snapshot.go#L62)):</sup>
Whoops. Removed.

---

<sup>**[snapshot.go, line 94 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYx69nT6uvHTTd4FcY)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/06dbc058e567c83cd5799a39c355d79391d0a1d3/snapshot.go#L94)):</sup>
not originally part of pr, but Commented.

---

<sup>**[snapshot.go, line 122 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYxh2V-lfNWBpkWMhH)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/06dbc058e567c83cd5799a39c355d79391d0a1d3/snapshot.go#L122)):</sup>
Not originally part of pr, but Commented.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48)

**Comment by TauZero** [comment]
Review status: 6 of 9 files reviewed, 14 unresolved discussions, all commit checks successful.

---

<sup>**[guest.go, line 168 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYrsXGNUCqnRail0Rg)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L168)):</sup>
Privatized.

---

<sup>**[guest.go, line 259 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYs1nnVs2jhYxy9hTw)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L259)):</sup>
Privatized.

---

<sup>**[guest.go, line 275 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYty2mWdIcn7zDC6Q9)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L275)):</sup>
Privatized.

---

<sup>**[guest.go, line 335 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYvjgzigfyr3dd_K-h)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L335)):</sup>
Privatized

---

<sup>**[guestRunner.go, line 233 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYvuTjlspvexC5od3j)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guestRunner.go#L233)):</sup>
Privatized.

---

<sup>**[README.md, line 272 \[r16\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrZ1dYB2YHHplKM_8ua)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/fd02be42d22568a3db9b8e96a30337644a8ee232/README.md#L272)):</sup>
Privatized.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48)

**Comment by mmlb** [comment]
Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.
Reviewed files:
- container.go @ r12
- guest.go @ r26
- guestRunner.go @ r24
- http.go @ r26
- image.go @ r25
- jobLog.go @ r25
- metrics.go @ r25
- README.md @ r26
- snapshot.go @ r25

---

<sup>**[guest.go, line 114 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYqoA1itnL-nVcV2Mo)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L114)):</sup>
I got ya, yeah wasn't looking for a fix really.

---

<sup>**[guest.go, line 317 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYumKBaIa6cwxS9R7H)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L317)):</sup>
hmmm, I think I just had the `err` stuck in my eye/brain from above. Thanks.

---

<sup>**[guest.go, line 328 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYvS43TYbcNi2RTtoX)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/guest.go#L328)):</sup>
Seems fine, sorry about all the extra comments, but this is the first time I'm looking very much into mistify-agent and using this pr sort of as a _fireside chat_ ;)

---

<sup>**[metrics.go, line 52 \[r8\]](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48#-JrYpfNPoqHe2FjYF43I)** ([raw file](https://github.com/mistifyio/mistify-agent/blob/26ee45704cbfaa91aa76df571a0fbdaadc5b29fb/metrics.go#L52)):</sup>
sweeeeeet

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48)

**Comment by mmlb** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- rpc/image.go @ r27
- rpc/README.md @ r27

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-agent/48)

**Pull request merged**
